# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('min_moisture', models.FloatField()),
                ('max_moisture', models.FloatField()),
                ('last_watered', models.TimeField()),
                ('automatic_water', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('moisture', models.FloatField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termin8_django.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnsPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termin8_django.Plant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termin8_django.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('moisture', models.FloatField()),
                ('time_watered', models.TimeField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termin8_django.Plant')),
            ],
        ),
    ]
