# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termin8_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='userownsplant',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='userownsplant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wateringhistory',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='termin8_django.PlantType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='room',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='termin8_django.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='timestamp',
            field=models.TimeField(default='2017-01-01: 20:00:00'),
            preserve_default=False,
        ),
    ]
