# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termin8_django', '0002_auto_20170404_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorhistory',
            name='timestamp',
            field=models.TimeField(default=b'2017-04-04 19:09:24'),
        ),
        migrations.AlterField(
            model_name='wateringhistory',
            name='time_watered',
            field=models.TimeField(default=b'2017-04-04 19:09:24'),
        ),
    ]
