# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('announce_text', models.TextField(blank=True, verbose_name='Announce')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
